name: paramak_openmc_no
channels:
  - conda-forge
dependencies:
  - python=3.11
  - setuptools<81
  - numpy
  - cad_to_dagmc
  - cadquery
  - scipy
  - pandas
  - pyyaml
  - h5py
  - matplotlib
  - pyvista
  - openmc-plotter
  - pip
  - pip:
      - cadquery-direct-mesh-plugin>=0.1.0
      - -e ./submodules/paramak
      - -e ./submodules/openmc_plasma_source
